[build]
  publish = "_site"
  command = "echo $TEST_VAR && npm run build"

[[plugins]]
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
  output_path = "reports/lighthouse.html"

[[plugins]]
package = "@netlify/plugin-sitemap"
